### ISSUE TITLE
device_info raises AttributeError: '<device>' object has no attribute 'group' after update to v0.3.8

### ISSUE THREAD

**Issue by pataho** [JH-Soft-Technology/InelsForHass#29]
## Configuration

```yaml


```

## Describe the bug
After updating the integration to v0.3.8, entities (cover, light, switch) fail to be added.
The error occurs during the evaluation of device_info in entity.py, where the integration assumes that all device types provide .group.

However, several device classes (e.g., pyShutter, pySwitch, pyLight) do not define the group attribute.
This results in the integration failing while adding entities, and devices never appear in Home Assistant.

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 849, in _async_add_entity
    if device_info := entity.device_info:
                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels_rpc/entity.py", line 35, in device_info
    "suggested_area": self.device.group
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'pyLight' object has no attribute 'group'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 849, in _async_add_entity
    if device_info := entity.device_info:
                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels_rpc/entity.py", line 35, in device_info
    "suggested_area": self.device.group
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'pyShutter' object has no attribute 'group'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 849, in _async_add_entity
    if device_info := entity.device_info:
                      ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inels_rpc/entity.py", line 35, in device_info
    "suggested_area": self.device.group
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'pySwitch' object has no attribute 'group'

```

Could you please review and approve https://github.com/JH-Soft-Technology/pyinels/pull/30? @jhoralek

**Comment by jhoralek** [comment]
Closing. Fixt with [pyInle #PR31](https://github.com/JH-Soft-Technology/pyinels/pull/31)
